[build]
  functions = "netlify/functions"
  publish   = "."
  command   = "npm install"
 
[[redirects]]
  from = "/public/songs.json"
  to   = "/.netlify/functions/get-songs"
  status = 200
 
[[redirects]]
  from = "/api/upload-song"
  to   = "/.netlify/functions/upload-song"
  status = 200
 
[[redirects]]
  from = "/api/get-songs"
  to   = "/.netlify/functions/get-songs"
  status = 200
 
[[redirects]]
  from = "/api/delete-song"
  to   = "/.netlify/functions/delete-song"
  status = 200
 
[[headers]]
  for = "/.netlify/blobs/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=86400"
